-- Engram schema for PostgreSQL + pgvector.
-- SQLite deployments get the equivalent DDL auto-generated by SQLAlchemy;
-- this file is the production shape (real vector column + HNSW index).

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS workspaces (
    id          VARCHAR(32) PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    slug        VARCHAR(200) NOT NULL UNIQUE,
    created_at  VARCHAR(40)  NOT NULL
);

CREATE TABLE IF NOT EXISTS memories (
    id               VARCHAR(32) PRIMARY KEY,
    workspace_id     VARCHAR(32) NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    type             VARCHAR(40)  NOT NULL DEFAULT 'note',
    title            VARCHAR(300) NOT NULL DEFAULT '',
    content          TEXT         NOT NULL,
    summary          TEXT         NOT NULL DEFAULT '',
    keywords_json    TEXT         NOT NULL DEFAULT '[]',
    tags_json        TEXT         NOT NULL DEFAULT '[]',
    source           VARCHAR(500) NOT NULL DEFAULT '',
    author           VARCHAR(200) NOT NULL DEFAULT '',
    embedding_json   TEXT         NOT NULL DEFAULT '[]',
    embedding        vector(256),          -- populated by trigger/app on Postgres
    importance       DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    confidence       DOUBLE PRECISION NOT NULL DEFAULT 0.8,
    access_count     INTEGER      NOT NULL DEFAULT 0,
    archived         INTEGER      NOT NULL DEFAULT 0,
    created_at       VARCHAR(40)  NOT NULL,
    updated_at       VARCHAR(40)  NOT NULL,
    last_accessed_at VARCHAR(40)  NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_memories_workspace ON memories(workspace_id);
CREATE INDEX IF NOT EXISTS ix_memories_type      ON memories(type);
CREATE INDEX IF NOT EXISTS ix_memories_created   ON memories(created_at);
CREATE INDEX IF NOT EXISTS ix_memories_archived  ON memories(archived);
-- ANN index for large workspaces:
CREATE INDEX IF NOT EXISTS ix_memories_embedding ON memories
    USING hnsw (embedding vector_cosine_ops);

CREATE TABLE IF NOT EXISTS memory_chunks (
    id             VARCHAR(32) PRIMARY KEY,
    memory_id      VARCHAR(32) NOT NULL REFERENCES memories(id) ON DELETE CASCADE,
    position       INTEGER     NOT NULL DEFAULT 0,
    content        TEXT        NOT NULL,
    embedding_json TEXT        NOT NULL DEFAULT '[]',
    embedding      vector(256)
);
CREATE INDEX IF NOT EXISTS ix_chunks_memory ON memory_chunks(memory_id);

CREATE TABLE IF NOT EXISTS entities (
    id            VARCHAR(32) PRIMARY KEY,
    workspace_id  VARCHAR(32) NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    name          VARCHAR(200) NOT NULL,
    kind          VARCHAR(40)  NOT NULL DEFAULT 'concept',
    mention_count INTEGER      NOT NULL DEFAULT 0,
    created_at    VARCHAR(40)  NOT NULL,
    UNIQUE (workspace_id, name)
);

CREATE TABLE IF NOT EXISTS memory_entities (
    id        VARCHAR(32) PRIMARY KEY,
    memory_id VARCHAR(32) NOT NULL REFERENCES memories(id) ON DELETE CASCADE,
    entity_id VARCHAR(32) NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
    UNIQUE (memory_id, entity_id)
);

CREATE TABLE IF NOT EXISTS relationships (
    id           VARCHAR(32) PRIMARY KEY,
    workspace_id VARCHAR(32) NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    source_id    VARCHAR(32) NOT NULL REFERENCES memories(id) ON DELETE CASCADE,
    target_id    VARCHAR(32) NOT NULL REFERENCES memories(id) ON DELETE CASCADE,
    kind         VARCHAR(40) NOT NULL DEFAULT 'related_to',
    weight       DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    created_at   VARCHAR(40) NOT NULL,
    UNIQUE (source_id, target_id, kind)
);

CREATE TABLE IF NOT EXISTS audit_log (
    id           VARCHAR(32) PRIMARY KEY,
    workspace_id VARCHAR(32)  NOT NULL DEFAULT '',
    actor        VARCHAR(200) NOT NULL DEFAULT 'anonymous',
    action       VARCHAR(80)  NOT NULL,
    detail       TEXT         NOT NULL DEFAULT '',
    created_at   VARCHAR(40)  NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_audit_ws ON audit_log(workspace_id);
